#!/bin/bash

# path of jar if module loaded
JAR=$(module display apps/picard_tools 2>&1 | perl -ne 'if(m/java/ && m/\s(\/\S+picard\.jar\b)/){print "$1\n"}' | head -1)

# path of jar otherwise
if [ -z "$JAR" ]
then
 JAR="/share/apps/picard_tools/2.5.0/picard.jar"
fi

# important: always do "$@"
java $JAVA_OPTIONS -jar $JAR "$@"
