#!/bin/bash

# path of jar if module loaded
JAR=$(module display apps/picard_tools 2>&1 | perl -ne 'if(m/java/ && m/\s(\/\S+picard\.jar\b)/){print "$1\n"}' | head -1)

# path of jar otherwise
if [ -z "$JAR" ]
then
 JAR="/home/sequencing/andpetzo/tools/picard-2.9.4.jar"
fi

# important: always do "$@"
/usr/lib/jvm/java-8-oracle/jre/bin/java $JAVA_OPTIONS -jar $JAR "$@"
