#!/bin/bash

# if CELLRANGER_VERSION not set find latest version installed at /share/apps/cellranger
if [ -z "$CELLRANGER_VDJ_VERSION" ]
then
	(unalias ls >& /dev/null) || true
	path=$((ls -rtd /share/apps/cellranger_vdj/* | tail -1) 2> /dev/null)
	if [ -z "$path" ]
	then
		>&2 echo "Cannot find installed cellranger vdj versions at /share/apps/cellranger_vdj"
		exit 1
	fi
	version=$(basename "$path")
else
	path="/share/apps/cellranger_vdj/$CELLRANGER_VDJ_VERSION"
	version="$CELLRANGER_VDJ_VERSION"
	if [ ! -e $path ]
	then
		>&2 echo "Cannot find installed cellranger vdj versions at /share/apps/cellranger_vdj"
		exit 1
	fi
fi

install_date=$(stat $path | grep "^Modify" | awk '{print $2}')

if [ ! -f "$path/sourceme.bash" ]
then
	>&2 echo "Cellranger vdj version installed at $path does not have a sourceme.bash to load before start!"
	exit 1
fi

>&2 echo "/apps/cellranger_vdj/$version $install_date"

source $path/sourceme.bash
export SGE_CLUSTER_NAME=biocluster3
cellranger "$@"
