#!/usr/bin/env Rscript

# reorders the library paths so that user paths will be the last place to look for libraries
lib_paths = .libPaths()
home_last_order = order(grepl('^/home',.libPaths()))
.libPaths(lib_paths[home_last_order])

library(Seurat)
library(dplyr)
library(tidyr)
library(Matrix)
library(readr)

#############
# Arguments #
#############

arguments = commandArgs(trailingOnly = F)
# get path to script
script_index = grep("--file",arguments)
script_dir = dirname(sub("--file=","",arguments[script_index]))
# get rid of leading arguments
arguments_length = length(arguments)
arguments_index = grep("--args",arguments)[1]
if(is.na(arguments_index)){
	arguments_index=arguments_length
} else{
	arguments_index=arguments_index+1
}
arguments = arguments[arguments_index:arguments_length]
if(length(arguments)<2){
	stop("Needs an output prefix and at least one raw stats file generated by one or more picard tools calls\n", call.=FALSE)
}

output_prefix = arguments[1]
raw_stats_files = arguments[2:length(arguments)]


# load batch stats and break text files into parts starting with '# picard.analysis.'
records = list()

for(raw_stats_file in raw_stats_files){
	rec = readChar(raw_stats_file, file.info(raw_stats_file)$size)
	rec = unlist(strsplit(rec,"# picard.analysis."))
	rec = sapply(rec,function(x){
    x = trimws(x)
    lines = unlist(strsplit(x,"\\n"))
    lines = grep("^#?\\s",lines,invert=T,value=T)
    lines = lines[which(nchar(lines)>0)]
    lines
	})
	records = c(records,rec)
}
names(records) = 1:length(records)

# parse gathermolecularbarcodedistribution
gathermolecularbarcodedistribution_idx = which(sapply(1:length(records),function(x){any(grepl("^GatherMolecularBarcodeDistributionByGene",head(records[[x]],1)))}))
gathermolecularbarcodedistribution= lapply(gathermolecularbarcodedistribution_idx,function(idx){
    metrics = list()
    input_lines = records[[idx]]
    input_lines = input_lines[2:length(input_lines)]    
    read.table(text=paste(input_lines,collapse="\n"),sep="\t",header=T,stringsAsFactors=F,check.names=F)
}) %>% bind_rows()

write.table(gathermolecularbarcodedistribution,file=paste(output_prefix,"umidistribution_by_cellbarcode.csv",sep="/"),row.names=F,col.names=T,quote=F,sep="\t")

# parse collectrnaseqmetrics output
collectrnaseqmetrics_idx = which(sapply(1:length(records),function(x){any(grepl("^CollectRnaSeqMetrics",head(records[[x]],1)))}))
collectrnaseqmetrics_parsed = lapply(collectrnaseqmetrics_idx,function(idx){
    metrics = list()
    input_lines = records[[idx]]
    input_lines = input_lines[2:length(input_lines)]    
    histogram_start_line = grep("^## HISTOGRAM",input_lines)
    metrics[['stats']] = read.table(text=paste(input_lines[1:histogram_start_line],collapse="\n"),sep="\t",header=T,stringsAsFactors=F,check.names=F) %>% filter(nchar(SAMPLE)>0)
    df = read.table(text=paste(input_lines[histogram_start_line:length(input_lines)],collapse="\n"),sep="\t",header=T,stringsAsFactors=F,check.names=F)
    col_df_nms = gsub("\\.normalized_coverage","",colnames(df))
    colnames(df) = col_df_nms
    df[['All_Reads']] = NULL
    metrics[['histogram']] = df
    metrics
})

collectrnaseqmetrics_final = list()
collectrnaseqmetrics_stats = lapply(collectrnaseqmetrics_parsed,function(x){x$stats}) %>% bind_rows()
collectrnaseqmetrics_stats$LIBRARY = NULL
collectrnaseqmetrics_stats$READ_GROUP = NULL

write.table(collectrnaseqmetrics_stats,file=paste(output_prefix,"rnaseqmetrics_by_cellbarcode.csv",sep="/"),row.names=F,col.names=T,quote=F,sep="\t")

collectrnaseqmetrics_histogram = lapply(collectrnaseqmetrics_parsed,function(x){x$histogram}) %>% bind_cols()
idx = grep("normalized_position\\d+",colnames(collectrnaseqmetrics_histogram),invert=T)
collectrnaseqmetrics_histogram = collectrnaseqmetrics_histogram[,idx]

write.table(collectrnaseqmetrics_histogram,file=paste(output_prefix,"rnaseqcoverage_by_cellbarcode.csv",sep="/"),row.names=F,col.names=T,quote=F,sep="\t")


# parse collectalignmentsummarymetrics output
collectalignmentsummarymetrics_idx = which(sapply(1:length(records),function(x){any(grepl("^CollectAlignmentSummaryMetrics",head(records[[x]],1)))}))
collectalignmentsummarymetrics= lapply(collectalignmentsummarymetrics_idx,function(idx){
    metrics = list()
    print(idx)
    input_lines = records[[idx]]
    input_lines = input_lines[2:length(input_lines)]
    read.table(text=paste(input_lines,collapse="\n"),sep="\t",header=T,stringsAsFactors=F,check.names=F,fill=T) %>% filter(nchar(SAMPLE)>0)
}) %>% bind_rows()

collectalignmentsummarymetrics$LIBRARY = NULL
collectalignmentsummarymetrics$READ_GROUP = NULL

write.table(collectalignmentsummarymetrics,file=paste(output_prefix,"alignmentsummarymetrics_by_cellbarcode.csv",sep="/"),row.names=F,col.names=T,quote=F,sep="\t")
